name: Build RSDKv4
on:
  push:
    branches:
      - master

jobs:
  msys2-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
      - shell: msys2 {0}
        name: Install new dependencies
        run : |
          pacman --noconfirm -U make
      - name: Compile the project
        run : |
          set MSYSTEM=MINGW64
          msys2 -c 'make CXX=x86_64-w64-mingw32-g++ CXXFLAGS=-static'
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./bin/*.exe ./artifacts 
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: msys2-windows-x64
          path: artifacts   
  v4-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libvorbis-dev libsdl2-dev
      - name: Build RSDKv4
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: v4-linux
          path: bin
